# Generated by Django 4.2.16 on 2024-10-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_2.player'),
        ),
        migrations.AddField(
            model_name='prize',
            name='received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
